import sqlite3

def create_blog_db():
    con = sqlite3.connect('database.db')
    print("Opened database successfully")
    cur = con.cursor()

    cur.execute("DROP TABLE blog")

    cur.execute("""
        CREATE TABLE blog (
            blog_post_id    INTEGER PRIMARY KEY NOT NULL,
            date    TEXT    NOT NULL,
            title   TEXT    NOT NULL,
            body    TEXT,
            image   BLOB,
            image_url   TEXT
        );
    """)

    print("Created table.")
    con.close()


def insert_blog_post(post):
    con = sqlite3.connect('database.db')
    cur = con.cursor()

    cur.execute("INSERT INTO blog (date, title, body) VALUES (?,?,?)",
        (post['date'],
        post['title'],
        post['body'])
    )

    con.commit()
    print("blog post added")
    con.close


post_1 = {
    "date" : "10-01-2022",
    "title" : "This is a Test Blog Post #1",
    "body" : """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt dui ut ornare lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Sed adipiscing diam donec adipiscing tristique. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Viverra tellus in hac habitasse platea. Et tortor at risus viverra adipiscing at in. Nulla pellentesque dignissim enim sit amet venenatis urna. Id donec ultrices tincidunt arcu non sodales neque sodales. Elit duis tristique sollicitudin nibh sit amet commodo. Quisque egestas diam in arcu cursus euismod quis. Ornare lectus sit amet est placerat in egestas erat imperdiet. Viverra maecenas accumsan lacus vel facilisis volutpat est. Morbi non arcu risus quis varius quam quisque id diam. Habitant morbi tristique senectus et netus et.

    Aliquet lectus proin nibh nisl condimentum id venenatis a. Netus et malesuada fames ac turpis egestas integer eget. Nibh tellus molestie nunc non blandit massa enim nec. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Cras semper auctor neque vitae tempus. Bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tincidunt eget nullam non nisi. Velit ut tortor pretium viverra suspendisse potenti nullam. Ac ut consequat semper viverra nam libero justo laoreet sit. Cras semper auctor neque vitae tempus quam pellentesque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus sit amet volutpat consequat mauris nunc. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hendrerit gravida rutrum quisque non tellus. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.

    Neque laoreet suspendisse interdum consectetur libero. Faucibus ornare suspendisse sed nisi lacus sed viverra. Sit amet consectetur adipiscing elit ut. Orci sagittis eu volutpat odio facilisis mauris. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Duis convallis convallis tellus id interdum velit laoreet id. Non enim praesent elementum facilisis leo vel fringilla. Eu consequat ac felis donec. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Id volutpat lacus laoreet non curabitur gravida. Ultrices sagittis orci a scelerisque purus semper. Gravida quis blandit turpis cursus in.

    Enim sit amet venenatis urna. Fames ac turpis egestas sed tempus. Augue ut lectus arcu bibendum at varius vel pharetra. Amet justo donec enim diam vulputate ut pharetra. Ante metus dictum at tempor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Malesuada fames ac turpis egestas integer eget aliquet. Pretium viverra suspendisse potenti nullam. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Amet volutpat consequat mauris nunc congue nisi vitae. Scelerisque felis imperdiet proin fermentum. Urna duis convallis convallis tellus id interdum velit. Amet nisl suscipit adipiscing bibendum est. Suspendisse interdum consectetur libero id faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Faucibus a pellentesque sit amet porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Scelerisque eu ultrices vitae auctor eu augue.

    Eu feugiat pretium nibh ipsum consequat. Quis eleifend quam adipiscing vitae proin. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Consectetur lorem donec massa sapien. Volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero volutpat sed. Ac turpis egestas integer eget aliquet nibh. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Varius quam quisque id diam vel quam elementum pulvinar. Maecenas volutpat blandit aliquam etiam erat. Adipiscing tristique risus nec feugiat in fermentum posuere. Leo in vitae turpis massa sed elementum tempus egestas. Tristique sollicitudin nibh sit amet commodo nulla. Aliquet bibendum enim facilisis gravida neque convallis a."""
}

post_2 = {
    "date" : "10-02-2022",
    "title" : "This is a Test Blog Post #2",
    "body" : """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt dui ut ornare lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Sed adipiscing diam donec adipiscing tristique. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Viverra tellus in hac habitasse platea. Et tortor at risus viverra adipiscing at in. Nulla pellentesque dignissim enim sit amet venenatis urna. Id donec ultrices tincidunt arcu non sodales neque sodales. Elit duis tristique sollicitudin nibh sit amet commodo. Quisque egestas diam in arcu cursus euismod quis. Ornare lectus sit amet est placerat in egestas erat imperdiet. Viverra maecenas accumsan lacus vel facilisis volutpat est. Morbi non arcu risus quis varius quam quisque id diam. Habitant morbi tristique senectus et netus et.

    Aliquet lectus proin nibh nisl condimentum id venenatis a. Netus et malesuada fames ac turpis egestas integer eget. Nibh tellus molestie nunc non blandit massa enim nec. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Cras semper auctor neque vitae tempus. Bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tincidunt eget nullam non nisi. Velit ut tortor pretium viverra suspendisse potenti nullam. Ac ut consequat semper viverra nam libero justo laoreet sit. Cras semper auctor neque vitae tempus quam pellentesque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus sit amet volutpat consequat mauris nunc. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hendrerit gravida rutrum quisque non tellus. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.

    Neque laoreet suspendisse interdum consectetur libero. Faucibus ornare suspendisse sed nisi lacus sed viverra. Sit amet consectetur adipiscing elit ut. Orci sagittis eu volutpat odio facilisis mauris. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Duis convallis convallis tellus id interdum velit laoreet id. Non enim praesent elementum facilisis leo vel fringilla. Eu consequat ac felis donec. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Id volutpat lacus laoreet non curabitur gravida. Ultrices sagittis orci a scelerisque purus semper. Gravida quis blandit turpis cursus in.

    Enim sit amet venenatis urna. Fames ac turpis egestas sed tempus. Augue ut lectus arcu bibendum at varius vel pharetra. Amet justo donec enim diam vulputate ut pharetra. Ante metus dictum at tempor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Malesuada fames ac turpis egestas integer eget aliquet. Pretium viverra suspendisse potenti nullam. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Amet volutpat consequat mauris nunc congue nisi vitae. Scelerisque felis imperdiet proin fermentum. Urna duis convallis convallis tellus id interdum velit. Amet nisl suscipit adipiscing bibendum est. Suspendisse interdum consectetur libero id faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Faucibus a pellentesque sit amet porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Scelerisque eu ultrices vitae auctor eu augue.

    Eu feugiat pretium nibh ipsum consequat. Quis eleifend quam adipiscing vitae proin. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Consectetur lorem donec massa sapien. Volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero volutpat sed. Ac turpis egestas integer eget aliquet nibh. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Varius quam quisque id diam vel quam elementum pulvinar. Maecenas volutpat blandit aliquam etiam erat. Adipiscing tristique risus nec feugiat in fermentum posuere. Leo in vitae turpis massa sed elementum tempus egestas. Tristique sollicitudin nibh sit amet commodo nulla. Aliquet bibendum enim facilisis gravida neque convallis a."""
}

post_3 = {
    "date" : "10-03-2022",
    "title" : "This is a Test Blog Post #3",
    "body" : """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt dui ut ornare lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Sed adipiscing diam donec adipiscing tristique. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Viverra tellus in hac habitasse platea. Et tortor at risus viverra adipiscing at in. Nulla pellentesque dignissim enim sit amet venenatis urna. Id donec ultrices tincidunt arcu non sodales neque sodales. Elit duis tristique sollicitudin nibh sit amet commodo. Quisque egestas diam in arcu cursus euismod quis. Ornare lectus sit amet est placerat in egestas erat imperdiet. Viverra maecenas accumsan lacus vel facilisis volutpat est. Morbi non arcu risus quis varius quam quisque id diam. Habitant morbi tristique senectus et netus et.

    Aliquet lectus proin nibh nisl condimentum id venenatis a. Netus et malesuada fames ac turpis egestas integer eget. Nibh tellus molestie nunc non blandit massa enim nec. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Cras semper auctor neque vitae tempus. Bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tincidunt eget nullam non nisi. Velit ut tortor pretium viverra suspendisse potenti nullam. Ac ut consequat semper viverra nam libero justo laoreet sit. Cras semper auctor neque vitae tempus quam pellentesque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus sit amet volutpat consequat mauris nunc. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hendrerit gravida rutrum quisque non tellus. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.

    Neque laoreet suspendisse interdum consectetur libero. Faucibus ornare suspendisse sed nisi lacus sed viverra. Sit amet consectetur adipiscing elit ut. Orci sagittis eu volutpat odio facilisis mauris. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Duis convallis convallis tellus id interdum velit laoreet id. Non enim praesent elementum facilisis leo vel fringilla. Eu consequat ac felis donec. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Id volutpat lacus laoreet non curabitur gravida. Ultrices sagittis orci a scelerisque purus semper. Gravida quis blandit turpis cursus in.

    Enim sit amet venenatis urna. Fames ac turpis egestas sed tempus. Augue ut lectus arcu bibendum at varius vel pharetra. Amet justo donec enim diam vulputate ut pharetra. Ante metus dictum at tempor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Malesuada fames ac turpis egestas integer eget aliquet. Pretium viverra suspendisse potenti nullam. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Amet volutpat consequat mauris nunc congue nisi vitae. Scelerisque felis imperdiet proin fermentum. Urna duis convallis convallis tellus id interdum velit. Amet nisl suscipit adipiscing bibendum est. Suspendisse interdum consectetur libero id faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Faucibus a pellentesque sit amet porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Scelerisque eu ultrices vitae auctor eu augue.

    Eu feugiat pretium nibh ipsum consequat. Quis eleifend quam adipiscing vitae proin. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Consectetur lorem donec massa sapien. Volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero volutpat sed. Ac turpis egestas integer eget aliquet nibh. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Varius quam quisque id diam vel quam elementum pulvinar. Maecenas volutpat blandit aliquam etiam erat. Adipiscing tristique risus nec feugiat in fermentum posuere. Leo in vitae turpis massa sed elementum tempus egestas. Tristique sollicitudin nibh sit amet commodo nulla. Aliquet bibendum enim facilisis gravida neque convallis a."""
}

post_4 = {
    "date" : "10-04-2022",
    "title" : "This is a Test Blog Post #4",
    "body" : """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt dui ut ornare lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Sed adipiscing diam donec adipiscing tristique. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Viverra tellus in hac habitasse platea. Et tortor at risus viverra adipiscing at in. Nulla pellentesque dignissim enim sit amet venenatis urna. Id donec ultrices tincidunt arcu non sodales neque sodales. Elit duis tristique sollicitudin nibh sit amet commodo. Quisque egestas diam in arcu cursus euismod quis. Ornare lectus sit amet est placerat in egestas erat imperdiet. Viverra maecenas accumsan lacus vel facilisis volutpat est. Morbi non arcu risus quis varius quam quisque id diam. Habitant morbi tristique senectus et netus et.

    Aliquet lectus proin nibh nisl condimentum id venenatis a. Netus et malesuada fames ac turpis egestas integer eget. Nibh tellus molestie nunc non blandit massa enim nec. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Cras semper auctor neque vitae tempus. Bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tincidunt eget nullam non nisi. Velit ut tortor pretium viverra suspendisse potenti nullam. Ac ut consequat semper viverra nam libero justo laoreet sit. Cras semper auctor neque vitae tempus quam pellentesque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus sit amet volutpat consequat mauris nunc. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hendrerit gravida rutrum quisque non tellus. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.

    Neque laoreet suspendisse interdum consectetur libero. Faucibus ornare suspendisse sed nisi lacus sed viverra. Sit amet consectetur adipiscing elit ut. Orci sagittis eu volutpat odio facilisis mauris. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Duis convallis convallis tellus id interdum velit laoreet id. Non enim praesent elementum facilisis leo vel fringilla. Eu consequat ac felis donec. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Id volutpat lacus laoreet non curabitur gravida. Ultrices sagittis orci a scelerisque purus semper. Gravida quis blandit turpis cursus in.

    Enim sit amet venenatis urna. Fames ac turpis egestas sed tempus. Augue ut lectus arcu bibendum at varius vel pharetra. Amet justo donec enim diam vulputate ut pharetra. Ante metus dictum at tempor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Malesuada fames ac turpis egestas integer eget aliquet. Pretium viverra suspendisse potenti nullam. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Amet volutpat consequat mauris nunc congue nisi vitae. Scelerisque felis imperdiet proin fermentum. Urna duis convallis convallis tellus id interdum velit. Amet nisl suscipit adipiscing bibendum est. Suspendisse interdum consectetur libero id faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Faucibus a pellentesque sit amet porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Scelerisque eu ultrices vitae auctor eu augue.

    Eu feugiat pretium nibh ipsum consequat. Quis eleifend quam adipiscing vitae proin. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Consectetur lorem donec massa sapien. Volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero volutpat sed. Ac turpis egestas integer eget aliquet nibh. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Varius quam quisque id diam vel quam elementum pulvinar. Maecenas volutpat blandit aliquam etiam erat. Adipiscing tristique risus nec feugiat in fermentum posuere. Leo in vitae turpis massa sed elementum tempus egestas. Tristique sollicitudin nibh sit amet commodo nulla. Aliquet bibendum enim facilisis gravida neque convallis a."""
}

post_5 = {
    "date" : "10-05-2022",
    "title" : "This is a Test Blog Post #5",
    "body" : """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Tincidunt dui ut ornare lectus. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Sed adipiscing diam donec adipiscing tristique. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Placerat vestibulum lectus mauris ultrices eros in cursus turpis. Viverra tellus in hac habitasse platea. Et tortor at risus viverra adipiscing at in. Nulla pellentesque dignissim enim sit amet venenatis urna. Id donec ultrices tincidunt arcu non sodales neque sodales. Elit duis tristique sollicitudin nibh sit amet commodo. Quisque egestas diam in arcu cursus euismod quis. Ornare lectus sit amet est placerat in egestas erat imperdiet. Viverra maecenas accumsan lacus vel facilisis volutpat est. Morbi non arcu risus quis varius quam quisque id diam. Habitant morbi tristique senectus et netus et.

    Aliquet lectus proin nibh nisl condimentum id venenatis a. Netus et malesuada fames ac turpis egestas integer eget. Nibh tellus molestie nunc non blandit massa enim nec. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Cras semper auctor neque vitae tempus. Bibendum ut tristique et egestas quis ipsum suspendisse. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Tincidunt eget nullam non nisi. Velit ut tortor pretium viverra suspendisse potenti nullam. Ac ut consequat semper viverra nam libero justo laoreet sit. Cras semper auctor neque vitae tempus quam pellentesque. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Lobortis scelerisque fermentum dui faucibus in ornare quam. Purus sit amet volutpat consequat mauris nunc. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Hendrerit gravida rutrum quisque non tellus. Velit laoreet id donec ultrices tincidunt arcu non sodales neque. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat.

    Neque laoreet suspendisse interdum consectetur libero. Faucibus ornare suspendisse sed nisi lacus sed viverra. Sit amet consectetur adipiscing elit ut. Orci sagittis eu volutpat odio facilisis mauris. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Mi bibendum neque egestas congue. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Duis convallis convallis tellus id interdum velit laoreet id. Non enim praesent elementum facilisis leo vel fringilla. Eu consequat ac felis donec. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Id volutpat lacus laoreet non curabitur gravida. Ultrices sagittis orci a scelerisque purus semper. Gravida quis blandit turpis cursus in.

    Enim sit amet venenatis urna. Fames ac turpis egestas sed tempus. Augue ut lectus arcu bibendum at varius vel pharetra. Amet justo donec enim diam vulputate ut pharetra. Ante metus dictum at tempor. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Malesuada fames ac turpis egestas integer eget aliquet. Pretium viverra suspendisse potenti nullam. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Amet volutpat consequat mauris nunc congue nisi vitae. Scelerisque felis imperdiet proin fermentum. Urna duis convallis convallis tellus id interdum velit. Amet nisl suscipit adipiscing bibendum est. Suspendisse interdum consectetur libero id faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Faucibus a pellentesque sit amet porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Scelerisque eu ultrices vitae auctor eu augue.

    Eu feugiat pretium nibh ipsum consequat. Quis eleifend quam adipiscing vitae proin. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Consectetur lorem donec massa sapien. Volutpat lacus laoreet non curabitur gravida arcu. Pulvinar mattis nunc sed blandit libero volutpat sed. Ac turpis egestas integer eget aliquet nibh. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Varius quam quisque id diam vel quam elementum pulvinar. Maecenas volutpat blandit aliquam etiam erat. Adipiscing tristique risus nec feugiat in fermentum posuere. Leo in vitae turpis massa sed elementum tempus egestas. Tristique sollicitudin nibh sit amet commodo nulla. Aliquet bibendum enim facilisis gravida neque convallis a."""
}

create_blog_db()

"""
insert_blog_post(post_1)
insert_blog_post(post_2)
insert_blog_post(post_3)
insert_blog_post(post_4)
insert_blog_post(post_5)
"""

print("Tasks complete")